apiVersion: v1
kind: Service
metadata:
  name: {{ include "kv.fullname" . }}-svc
  labels: {{- include "kv.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.kvPort }}
    name: kv
  - port: {{ .Values.raftPort }}
    name: raft
  clusterIP: None
  selector:
    app: {{ include "kv.fullname" . }}
