apiVersion: v1
kind: Service
metadata:
  name: {{- include "kv.fullname" . }}-headless
  labels:
    app: {{- include "kv.fullname" . }}
spec:
  ports:
  - port: {{ .Values.kvPort }}
    name: kv
  - port: {{ .Values.raftPort }}
    name: raft
  clusterIP: None
  selector:
    app: {{- include "kv.fullname" . }}
