apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kv.fullname" . }}
  labels: {{- include "kv.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "kv.fullname" . }}
  serviceName: {{ include "kv.fullname" . }}-svc
  replicas: {{ len .Values.initialCluster }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.kvPort }}"
      labels:
        app: {{ include "kv.fullname" . }}
    spec:
      volumes:
        - name: cluster-config
          configMap:
            name: {{ include "kv.fullname" . }}-cluster-config
      containers:
      - name: kv
        image: {{ include "kv.image" . }}
        ports:
        - containerPort: {{ .Values.raftPort }}
          name: raft
        - containerPort: {{ .Values.kvPort }}
          name: kv
        args:
          - --name=$(HOSTNAME)
          - -c=/etc/raft-kv/cluster.yaml
          - -d=/var/raft-kv
          - -v={{ .Values.logLevel }}
          - -l=0.0.0.0:{{ .Values.kvPort }}
          - -r=0.0.0.0:{{ .Values.raftPort }}
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: cluster-config
          mountPath: /etc/raft-kv/
        - name: data
          mountPath: /var/raft-kv/
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClass }}
      resources:
        requests:
          storage: {{ .Values.storageSize }}
