image:
  repository: yashulyak/raft-kv
  pullPolicy: IfNotPresent
  tag: latest

# dataDir will be mounted for each pod.
dataDir: /raft

storageSize: 5Gi
storageClass: standard

logLevel: debug

# id must be unique.

# raftPort is a grpc service that is used for internal comms
# it will be used with internal dns names and can be the same for every pod
# in the stateful set
raftPort: 4000

# kvPort is a http service for user requests
# all pods must be exposed therefore each one will have a service with a
# a distinct selector. this service will expose pods kvPort as exposeKvPortAs
kvPort: 4001

# externally visible address to expose services for clients
domain: 0.0.0.0

initialCluster:
  - id: 1
    exposeKvPortAs: 30001
    protocol: http
  - id: 2
    exposeKvPortAs: 30002
    protocol: http
  - id: 3
    exposeKvPortAs: 30003
    protocol: http
